"""AC5, behavioral half: L3 opens a PR via D5's real SourceControlService
(against its own mock GitHub server) and stops there -- no merge."""
from __future__ import annotations

from gates.pr_gate import L3PullRequestGate, OpenedPullRequest


def test_l3_opens_a_pr_and_returns_a_handle(source_control_service, mock_github):
    server, _ = mock_github
    server.state.refs[("acme", "app", "feature-x")] = "b" * 40

    gate = L3PullRequestGate(source_control_service)
    result = gate.open_pr_and_stop(
        tenant_id="tenant-acme", repository="acme/app", head_branch="feature-x", base_branch="main",
        title="Bump dependency X", description="Generated by the System; opened only, never merged.",
    )
    assert isinstance(result, OpenedPullRequest)
    assert result.state == "open"
    assert result.pr_number == 1
    assert result.url.endswith("/pull/1")


def test_l3_gate_reuses_an_existing_open_pr_without_opening_a_second_one(source_control_service, mock_github):
    server, _ = mock_github
    server.state.refs[("acme", "app", "feature-y")] = "c" * 40
    gate = L3PullRequestGate(source_control_service)

    first = gate.open_pr_and_stop(
        tenant_id="tenant-acme", repository="acme/app", head_branch="feature-y", base_branch="main",
        title="t", description="d",
    )
    second = gate.open_pr_and_stop(
        tenant_id="tenant-acme", repository="acme/app", head_branch="feature-y", base_branch="main",
        title="t", description="d",
    )
    assert second.pr_number == first.pr_number


def test_l3_gate_class_exposes_no_merge_or_deploy_capable_method():
    """Structural spot-check (see test_l3_floor_fitness.py for the
    exhaustive, repo-wide version): the only public method on this
    class that talks to source control at all is `open_pr_and_stop`."""
    public_methods = [name for name in dir(L3PullRequestGate) if not name.startswith("_")]
    assert public_methods == ["open_pr_and_stop"]
    for forbidden in ("merge", "close_pr", "deploy"):
        assert not hasattr(L3PullRequestGate, forbidden)
