"""Get file/module summary (spec Sec. 6.3): return a generated summary
instead of full file contents -- this server never hands back whole
files, only structural summaries built from the already-parsed symbol
table.
"""
from __future__ import annotations

from .model import Definition

GENERATED_SUFFIXES = ("_pb2.py", ".pb.go", ".g.dart", ".g.ts", "_generated.py", ".min.js")
GENERATED_MARKERS = ("@generated", "DO NOT EDIT", "Code generated by")


def is_generated(path: str, source_head: str) -> bool:
    if path.endswith(GENERATED_SUFFIXES):
        return True
    return any(marker in source_head for marker in GENERATED_MARKERS)


def summarize(path: str, definitions: list[Definition], line_count: int, generated: bool) -> str:
    if not definitions:
        return f"{path}: {line_count} lines, no top-level definitions indexed."
    by_kind: dict[str, list[str]] = {}
    for d in definitions:
        by_kind.setdefault(d.kind, []).append(d.name)
    parts = [f"{path}: {line_count} lines, {len(definitions)} symbol(s)."]
    for kind in ("class", "interface", "function", "method", "type", "constant", "variable"):
        names = by_kind.get(kind)
        if names:
            shown = ", ".join(names[:8])
            more = f" (+{len(names) - 8} more)" if len(names) > 8 else ""
            parts.append(f"{kind}s: {shown}{more}.")
    if generated:
        parts.append("This file is machine-generated -- summarized, not returned whole (Sec. 6.3).")
    return " ".join(parts)
